In [48]:
import numpy as np
import matplotlib.pyplot as plt
import math
# theta1 = 0
# theta2 = 0
# theta3 = 0
L1 = 50
L2 = 135
L_tip = 147

x = 50
y = 10
z = 100
if(x> 150 or y>150 or z>150):
    print("ReEnter Coordinates as Given are out of workspace")
P_2 = (x+y)**2+(z-L1)**2

C3 = (P_2-L2**2-L_tip**2)/(2*(L2*L_tip))
print("C3",C3)

r = L2 + (L_tip*C3)

a = z-L1

#C3 = (p_2 - L2**2 - L_tip**2) /(2*L2*L_tip)
theta1 = math.atan(y/x)

b = x/np.cos(theta1)

theta2 = 2*math.atan((b + (b**2 + a**2 - r**2)**0.5) / (r+a))
theta3 = math.atan((1 - C3**2)**0.5 / C3)
print(math.degrees(theta1),math.degrees(theta2) ,math.degrees(theta3) )

x1 = L2*C1*S2 + L_tip*C1*(C2*S3 + S2*C3)
y1 = L2*S1*S2 + L_tip*S1*(S2*C3 + C2*S3)
z1 = L1 + L_tip*(C2*C3 - S2*S3) + L2*C2
C1 = np.cos(theta1)
C2 = np.cos(theta2)
C3 = np.cos(theta3)
S1 = np.sin(theta1)
S2 = np.sin(theta2)
S3 = np.sin(theta3)
print(x1,y1,z1)

T0_1= [[np.cos(theta1), -np.sin(theta1),0.0, 0.0 ],
       [np.sin(theta1), np.cos(theta1),0.0, 0.0],
       [0.0, 0.0, 1.0, L1],
       [0.0, 0.0, 0.0, 1.0]]
T1_2= [[np.sin(theta2), np.cos(theta2), 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0],
       [np.cos(theta2), -np.sin(theta2), 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0]]
T2_3= [[np.cos(theta3), -np.sin(theta3), 0.0, L2],
       [np.sin(theta3), np.cos(theta3), 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, 1.0]]
T3_ef=[[1.0, 0.0, 0.0, L_tip],
       [0.0, 1.0, 1.0, 0.0],
       [0.0, 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, 1.0]]
T0_2 = np.matmul(T0_1,T1_2)
T0_3 = np.matmul(T0_2,T2_3)

T0_ef = np.matmul(T0_3,T3_ef)
C1 = np.cos(theta1)
C2 = np.cos(theta2)
C3 = np.cos(theta3)
S1 = np.sin(theta1)
S2 = np.sin(theta2)
S3 = np.sin(theta3)


print(T0_ef)

C3 -0.8499370118417737
11.309932474020215 127.4642726317232 -31.79518089447355
54.02590149784495 10.805180299568994 105.3574750692168
[[ 9.75784659e-01 -9.68646535e-02 -2.92980789e-01  2.48513414e+02]
 [ 1.95156932e-01 -1.93729307e-02  9.61207745e-01  4.97026828e+01]
 [-9.87829516e-02 -9.95109003e-01 -9.95109003e-01 -4.66370859e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
